### ISSUE TITLE
Translate III. Config

### ISSUE THREAD

**Issue by fernandes** [12factor/12factor-br#10]
Translate config https://github.com/12factor/12factor-br/blob/master/content/config.md

PR file as content/pt_br/config.md

**Comment by gwmoura** [comment]
translating

**Comment by gwmoura** [comment]
translated. @fernandes  acho que fiz algo errado quando sicronizei suas alterações, mas verifica e me fala.

**Comment by fernandes** [comment]
hahaha parece que zuou algo mesmo no pull, tu deu pull na master antes do commit e PR?

**Comment by gwmoura** [comment]
Rpz eu acho que me confundi na hora de atualizar meu repo local. Eu
adicionei um novo branch com chamado 12factor-br/master dei um pull, aí deu
pau no arquivo Gemfile, ajustei dei o merge, troquei a posição do arquivo
config.md para dentro de pt_br, qdo dei o commit do git rm, veio o catatau
de arquivo alterado, mas acho que que descobri o problema, acho que n
voltei para o meu branch origin/mastar e dei push com as alterações.

Resumindo fiz besteira.

Em dom, 8 de fev de 2015 23:11, Celso Fernandes <notifications@github.com>
escreveu:

**Comment by fernandes** [comment]
TL;DR fiz besteira, sensacional hahahaha

mas esquenta não, faz como comentamos no PR e go for it :)

**Comment by gwmoura** [comment]
Pronto, fiz o PR correto agora. @fernandes @lfilho podem verificar. :+1:

**Comment by fernandes** [comment]
ja fiz os comentários la :)
