### ISSUE TITLE
Translate IV. Backing Services

### ISSUE THREAD

**Issue by fernandes** [12factor/12factor-br#13]
Translate backing services https://github.com/12factor/12factor-br/blob/master/content/backing-services.md

PR file as content/pt_br/backing-services.md

**Comment by lfilho** [comment]
Eu pego essa :+1:

**Comment by fernandes** [comment]
valeu @lfilho 

btw, fiz o rebase la, agora ta tudo certinho :)

**Comment by lfilho** [comment]
PR pronto! https://github.com/12factor/12factor-br/pull/22
