### ISSUE TITLE
Repetições da palavra "Aplicações" e "Aplicação"

### ISSUE THREAD

**Issue by gwmoura** [12factor/12factor-br#14]
As palavras **aplicações** e **aplicação** se repetem muito, o que acham de derivar um pouco colocando sinônimos como software e app

**Comment by fernandes** [comment]
hummm na minha opinião software é muito genérico, app e apps eu ja acho tranquilo, apesar de ser uma abreviação para applications e não aplicações...

Se fosse um livro eu falaria para seguirmos com aplicações, mas para o 12factor.net utilizar app de vez em quando para não ficar tão massante o uso de aplicações é mais tranquilo.

**Comment by lfilho** [comment]
Nos arquivos que traduzi até agora só tinha "app" e deixei "app" mesmo...

**Comment by fernandes** [comment]
maravilha

**Comment by lfilho** [comment]
Podemos fechar essa issue aqui, então?

**Comment by gwmoura** [comment]
Por mim não tem problema não pode fechar.

Então ficou de certo de variar entre app(s) e aplicação(ões), correto?

**Comment by lfilho** [comment]
Creio que sim. Tô fazendo assim: quando é "application(s)" eu traduzo "aplicação(ões)", quando vem "app", eu deixo "app" mesmo.

**Comment by gwmoura** [comment]
Blz vou seguir o mesmo padrão. Quando terminar todas as traduções volto para revizar. vou abrir outra issue sobre a palvra twelve-factor

**Comment by lfilho** [comment]
Fechando essa aqui então, após longa data e consenso atingido. :wink:

**Comment by gwmoura** [comment]
:ok_hand: :wink:
