### ISSUE TITLE
Rebase com upstream / Suporte a traduções

### ISSUE THREAD

**Issue by lfilho** [12factor/12factor-br#15]
Olá pessoal. Não sei se já viram mas agora o heroku/12factor já suporta mecanismo oficial de tradução! E me disponho a ajudar na tradução para o nosso pt-br!

Todavia, será necessário fazer um rebase e alterar a estrutura física das pastas / nomes do arquivo, conforme podem ver lá no upstream...

Como pretendem fazer? Alguém se voluntaria? Eu sim, caso ninguém já não o esteja fazendo.
Me dando o sinal verde (ou as diretrizes da forma que preferirem), estou a postos.

**Comment by fernandes** [comment]
Olá @lfilho obrigado pela disponibilidade em auxiliar.

Tranquilo, pode deixar que eu faço o rebase (que ja era previsto) e acerto a estrutura... para auxiliar na tradução, estou abrindo issues dos capítulos restantes com a tag "help wanted", só comentar em uma issue que vai fazê-la que eu dou assignee, assim que mandar o PR eu fecho a issue.

**Comment by lfilho** [comment]
Beleza. No aguardo então ;)
