### ISSUE TITLE
Translate VI. Processes

### ISSUE THREAD

**Issue by gwmoura** [12factor/12factor-br#20]

**Comment by gwmoura** [comment]
Deixa comigo

**Comment by gwmoura** [comment]
Traduzindo, aguardando mergo do PR #18 para fazer o push

**Comment by fernandes** [comment]
:+1:

**Comment by lfilho** [comment]
Pq tá aguardando o merge do #18?

**Comment by lfilho** [comment]
Ah vi aqui... Você tá fazendo os PRs direto do master né? Sugiro fazer a partir de uma branch... Aí cada PR fica independente...

**Comment by fernandes** [comment]
não entendi seu último comentário @lfilho

**Comment by lfilho** [comment]
o @gwmoura está esperando o merge do outro pull request dele pra poder fazer o push do arquivo pertinente a esse PR aqui... Aí não entendi o porque disso... Aí fui ver e vi que ele tá abrindo o PR a partir da branch `master` do fork dele. Daí sugeri realizar os trabalhos de tradução usando branches separadas, independentes para cada arquivo traduzido... Assim cada branch (e, consequentemente, cada PR) ficam isolados e independentes entre si... Daí, por exemplo, esse PR aqui (Processes) não ia ficar dependendo da aprovação do outro (Config).

**Comment by fernandes** [comment]
a sim, saquei :+1:

**Comment by gwmoura** [comment]
Blz, farei isso, mas no ultimo commit q fiz, no PR #18, tem as ultimas
alterações do config e a alteração do conteúdo do processes. Da para fazer
o merge e a partir daqui crio uma alteração branch

Em sex, 20 de fev de 2015 14:23, Celso Fernandes <notifications@github.com>
escreveu:

**Comment by gwmoura** [comment]
Pessoal,

Desculpa a ausência, vai poder fazer o merge do jeito que falei?

**Comment by gwmoura** [comment]
Cancelei td que e abri um novo PR #37

**Comment by lfilho** [comment]
Vou fechar esse aqui então, ok? :+1:

**Comment by gwmoura** [comment]
pode fechar!
