### ISSUE TITLE
Padronização

### ISSUE THREAD

**Issue by fernandes** [12factor/12factor-br#24]
Olá @gwmoura e @lfilho 

Estive observando nossos últimos commits e percebi uma coisa, nós brasileiros adoramos americanizar tudo hahahahha no último PR #23 tem alguns termos em inglês, pensei em traduzi-los, tentarmos deixar o texto mais em português possível pensando no leitor que não sabe inglês.

Criei uma "tabelinha" de sugestões, e aguardo considerações dos Srs., podemos deixar que depois que decidirmos eu faço a revisão do que ficou pra trás :) - se tiver algo mais, me falem que vou incluindo na tabelinha até batermos o martelo :D

| Inglês | Português | Observação |
|---------|----------------|------------------|
| 12 factor | doze-fatores | principal termo a ser padronizados :) |
| deploy | implantação | |
| estágio de build | estágio de construção | |
| pacote executável conhecido como *build* | conhecido como artefato | ja vi em diversas referências o termos artefato, foi o melhor que pude pensar |
| A *release* resultante | O lançamento resultante |  |
| (também conhecido como "runtime") | tempo de execução | Esse termo é comum na bibliografia de computação |
| o timestamp da release | marcação de tempo | nunca vi, pensei nele |

Apenas ressaltando que se eu fosse enviar um e-mail para um colega ou lista de discussão, sim, eu usaria os termos em inglês dessa forma... penso mais em realizarmos de fato a maior tradução possível, e quando tiver algum termo em inglês que não soubermos como explicar, colocar em itálico e uma breve descritivo do lado para o leitor que não tem conhecimento de inglês.

obrigado e sugestões?

Edit:

### Tabela de Termos

| Inglês | Português |
|---------|----------------|
| 12 factor | doze-fatores |
| estágio de build | estágio de construção |
| runtime | tempo de execução |
| deploy | implantação |
| pacote executável conhecido como *build* | conhecido como artefato |
| A *release* resultante | O lançamento resultante |
| o timestamp da release | a data do lançamento |

**Comment by lfilho** [comment]
Opa. Ótima iniciativa! Também fiquei com essas dúvidas ao traduzir. Mas me tranquilizei em deixar em inglês os termos que não achei uma tradução direta por pensar que o público alvo é mesmo os desenvolvedores. Tem muita IDE, documentação de linguagem, plataformas, serviços e etc que são só em inglês! Creio que não tem como de alguém da nossa área não conhecer esses termos inglês...

Mais além, justamente por tais termos em inglês serem tão amplamente utilizados, se traduzirmo-los pode até gerar dúvidas ou confusões... Por exemplo: "o lançamento resultante" == "o lançamento de quê?". Já "a release resultante" já me aparenta mais claro e sei exatamente do que se está falando...

Outro exemplo que também fiquei nessa dúvida: deploy. Muitas empresas usam "implantação" em outro sentido. Há departamentos e equipes de implantação, que não seriam departamentos e equipes "de deploy", concordam? "Implantação" pode me dar a ideia da **atividade** de implantacão: de pegar um software e instalar em algum lugar, sabe? O deploy simples, local, na máquina do desenvolvedor seria apto a ser considerado uma "implantação"?

Estágio de build (Build, nesse caso seria um verbo) para construção, acho que convém traduzir mesmo. Fica bacana.

Já o build enquanto nome (pacote executável conhecido como build) não acho que traduz bem pra artefato. Também já vi referências a "artefato". Mas vejo da seguinte maneira: artefatos são resultados de um build e não o build em si. Ou vocês vem o build como um grande artefato? Acho que é mais questão semântica / de como cada um vê mesmo. Tô em cima do muro nessa.

**Comment by gwmoura** [comment]
Assim, eu acho uma boa explicar, justamente para o pessoal que ta chegando,
mas como o Luiz falou tem coisa não é bom traduzir, é bom sempre pensar
numa forma de que todos entendam, outra coisa, nos livros e nas palestras
eu vejo o pessoal usar muito os termos em inglês. Podemos perguntar aos
nossos colegas e ver o que maioria acha. Se a dificuldade em entender os
termos em inglês for grande, colocamos uma breve explicação caso contrário
continuamos como esta.

Em Thu Feb 12 2015 at 10:58:05, Luiz Gonzaga dos Santos Filho <
notifications@github.com> escreveu:

**Comment by lfilho** [comment]
Seria o caso de deixar em inglês com uma anotação para notas no rodapé? Por exemplo:

```
bla bla bla runtime* etc etc etc

etc etc 

etc

*runtime: "runtime" significa, literalmente, "tempo de execução". É quando....
```

**Comment by fernandes** [comment]
não, calma @gwmoura não é sair explicando tudo heheheh

eu tinha pensado em 2 pontos distintos:

1. traduzir os termos em inglês (vide minha tabelinha, o que chegarmos em um consenso)

2. termos que for bem difícil traduzir as vezes até mesmo pela ausência de significado, minha sugestão é ao invés de apenas deixar o termo em inglês fazer o seguinte (peguei deploy como exemplo apenas)

quando é feito o _deploy_ (processo de colocar uma app rodando em um servidor) acontece o xyz...

esses são os dois pontos hehehe

**Comment by lfilho** [comment]
Pode ser. Acho que fica legal. O desafio vai ser em escolher o que traduzir e o que deixar em inglês.
Da tabela acima, eu traduziria apenas `12 factor` e `runtime`. O resto eu deixaria em inglês com a explicação em inglês logo a seguir, entre parenteses - conforme exemplo do @fernandes

**Comment by fernandes** [comment]
maravilha, tu tinha falado do build também ali acima.

> agora que vi aqui: "Implantação" pode me dar a ideia da atividade de implantacão: de pegar um software e instalar em algum lugar, sabe?

sim, tipo pegar de um repositório e colocar no cloud server heheheh se é uma equipe, uma pessoa ou um software, é apenas uma questão de processo, imho

**Comment by gwmoura** [comment]
Iremos colocar os conceitos em todos os capítulos ou apenas no início?
Geralmente nos livros a explicação é no início, como uma referência.

Em Fri Feb 13 2015 at 13:46:44, Celso Fernandes <notifications@github.com>
escreveu:

**Comment by fernandes** [comment]
na verdade não é explicar conceitos, nem nada do tipo... a ideia são os termos em português, só isso hehehhe

caso não seja possível traduzir, colocamos entre parênteses uma breve explicação na primeira ocorrência, nada demais hehehhe

**Comment by lfilho** [comment]
Mas a "primeira ocorrência" a capítulo? Exemplo: digamos que "deploy" será uma dessas "intraduzíveis", mas ela seja citada no capítulo III e VI... Em ambos os capítulos nós faríamos os parênteses com a explicação?

**Comment by lfilho** [comment]
E ae, news?

**Comment by fernandes** [comment]
não sei, tinha pensado apenas na primeira ocorrência no livro como um todo. o ideal seria ter os termos em português e deixar o texto claro, se formos assumir que as pessoas conhecem os termos em inglês por utilizarem no dia a dia, quase nada precisa ser traduzido

**Comment by lfilho** [comment]
Mas e se alguém não ler na sequência? Será que vale a pena nos preocuparmos com isso?

Outra opção que pensei agora é criarmos um `glossario.md` e colocar esses termos não traduzidos, com as devidas explicações lá. Daí, colocaríamos apenas uma referência para este arquivo **toda vez** que um termo não traduzido for aparecer. Que acham?

**Comment by fernandes** [comment]
era uma sugestão para traduzirmos o máximo possível... ja ta complicando demais isso aqui hahahha

**Comment by lfilho** [comment]
@fernandes, mas isso todos nós concordamos (traduzir o máximo possível). A discussão é justamente sobre a melhor forma de se fazer com o que for intraduzível :sweat_smile:

**Comment by lfilho** [comment]
Ao meu ver as opções são:
a) `glossario.md` centralizando os intraduzíveis, e a cada `.md` traduzido que conter palavras intraduzíveis, referenciar o `glossario.md`
b) Na primeira (e somente na primeira) ocorrência de uma palavra intraduzível, explicar entre parênteses seu significado. Uma vez para todos os arquivos.
c) A cada ocorrência de uma palavra intraduzível, explicar entre parênteses seu significado. Uma vez por arquivo, para todos os arquivos.

Confere?

Eu voto na a) ou c). Na b) não pois os arquivos são linkados entre si, então um leitor pode "pular" a explicação de uma palavra em um arquivo ao seguir um link que leva pra um outro arquivo mais ao final do TOC...

**Comment by fernandes** [comment]
a) quebra a estrutura original, não sei se rola

vamos de (c) então? @gwmoura

**Comment by lfilho** [comment]
É, pensei nessa quebra da estrutura original também... Mas por outro lado esse `glossario.md` ficaria só na pasta `pt-br`. Então talvez o pessoal do upstream não se importe. Não obstante, se concordarmos que a existência desse arquivo é melhor para um melhor entendimento do 12factor em Português, creio que eles não se oporiam não...

**Comment by fernandes** [comment]
isso é verdade, muda só no pt... dentro do toc nosso, pode ser uma boa mesmo

**Comment by fernandes** [comment]
nesse caso, sem pensar na quebra de estrutura, vou de A hehehhe

**Comment by gwmoura** [comment]
Gostei da opção a) tb, podemos perguntar ao fabio kung, falei com ele para
ver com a equipe do 12-factor a questão da atualização e ele foi bem
solicito

Em sex, 20 de fev de 2015 14:17, Celso Fernandes <notifications@github.com>
escreveu:

**Comment by lfilho** [comment]
Legal.
E o que decidimos então? Contactemos o Fabio Kung ou tocamos no **a)** logo?

**Comment by fernandes** [comment]
não entendi o que perguntar ao @fabiokung (citei aqui, assim ele fica por dentro da thread, caso possa nos auxiliar)

acredito que colocando o glossario seria ok

**Comment by gwmoura** [comment]
Falar com ele, seria para dar uma opnião para ver o que o pessoal de lá
acha, algum de vocês sabe chinês ou Japonês, podemos olhar as traduções dos
colegas :D

hehehehehehehe

Em Tue Feb 24 2015 at 10:52:37, Celso Fernandes <notifications@github.com>
escreveu:

**Comment by fernandes** [comment]
agora ele ja esta em cópia... :)

eu até pensei nisso, dei uma olhada nas tradução, não achei um caracter compreensível hahaha

no final das contas, vamos traduzir tudo, depois lapidamos :joy:

**Comment by lfilho** [comment]
E aí, pessoal? Parei nas traduções esperando essas definições... :)

**Comment by fernandes** [comment]
vou definir os termos que mais se aproximam e seguimos com o texto todo em português, pode ser? assim ja resolvemos isso e o texto fica todo em português, sem precisar explicar termos ou ter tabela com o conteúdo

**Comment by lfilho** [comment]
Kkkkk mudo de novo? Blz...

**Comment by gwmoura** [comment]
É tb tinha parado, acho melhor adiantar e depois atualizamos ou mandar um
email para o Kung e esperar mais um pouco.

O que vcs acham?

Em sex, 13 de mar de 2015 09:52, Luiz Gonzaga dos Santos Filho <
notifications@github.com> escreveu:

**Comment by fernandes** [comment]
@lfilho mudei não, estava tentando chegar num consenso... não funcionou, tomei uma decisão na linha que acho mais acertada ;)

**Comment by lfilho** [comment]
https://github.com/12factor/12factor-br/issues/24#issuecomment-75278673 e o comentário subsequente... :)

Mas de boa, batamos o martelo e sigamos em frente. Melhor do que a parálise por análise que acabamos criando :P

**Comment by fernandes** [comment]
coloquei os termos equivalentes em português, depois volto nos capítulos anteriores revendo... agora podemos seguir em frente.

**Comment by fabiokung** [comment]
Desculpem a demora. Sinceramente não faço ideia do que o pessoal do projeto original acharia melhor. Pessoalmente gostei mais da opção a), mas não posso falar pelo time que mantem o repositório.

Minha sugestão é realmente não esquentar muito a cabeça com isso e seguir em frente com o que for mais fǻcil/simples de mudar depois caso precise. Quando for a hora do merge, se alguém não gostar vai dizer.
