### ISSUE TITLE
Translate X. Dev/prod parity

### ISSUE THREAD

**Issue by gwmoura** [12factor/12factor-br#32]

**Comment by lfilho** [comment]
:raising_hand: (tinha que ter um masculino desse também hehe)

**Comment by gwmoura** [comment]
Verdade!!! Hehehehe

Em sáb, 2 de mai de 2015 10:17, Luiz Gonzaga dos Santos Filho <
notifications@github.com> escreveu:

**Comment by lfilho** [comment]
@gwmoura Dica de github: quando responder por email, deleta o restante do email, pois corre o risco de acontecer o que aconteceu acima ó :arrow_heading_up: :blush: :+1:
