### ISSUE TITLE
Twelve-factor ou Doze-fator? Eis a questão!

### ISSUE THREAD

**Issue by gwmoura** [12factor/12factor-br#41]
Pessoal,

vi em algumas traduções vocês usando doze-fator ou doze-fatores, mas eu permaneci com a versão em inglês, vamos padronizar tudo para pt-br ou deixar o original?

Na minha opinião twelve-factor fica melhor, por ser um conceito já conhecido, os japoneses e koreanos deixaram twelve-factor também - http://12factor.net/ja/concurrency

O que acham?

**Comment by lfilho** [comment]
Eu estava deixando "doze-fatores" mesmo. Mas se concordarem, posso alterar os que já fiz...

**Comment by lfilho** [comment]
Vamos fechara essa issue? Todas as traduções estão ficando como "doze-fatores" mesmo, então acho q podemos seguir em frente e fechar esta issue... Que não concordar pode reabri-la a vontade e continuarmos a discussão :wink: :+1:

**Comment by gwmoura** [comment]
Tranquilo, vamos fechar sim, eu tinha colocado tudo twelve-factor, mas altero depois que traduzirmos tudo.

**Comment by lfilho** [comment]
Blz... Faz um search & replace all aí e pronto :stuck_out_tongue_winking_eye:
