### ISSUE TITLE
Envio final para o upstream do heroku

### ISSUE THREAD

**Issue by lfilho** [12factor/12factor-br#47]
@fernandes e @gwmoura sobre o envio final para o heroku... Mini plano:

- [x] 1) Atualizar nosso fork em relação do heroku
- [x] 2) Adicionar nossos nomes no Readme na seção de tradutores
- [x] 3) Ver o que mudou na documentação oficial em inglês desde então e atualizar traduções de acordo
- [x] 4) Abrir PR para o Heroku
- [x] 5) Retirar "WIP" do PR lá no Heroku: https://github.com/heroku/12factor/pull/23

Falta mais alguma coisa?

**Comment by lfilho** [comment]
Vou tentar fazer os dois primeiros ali, acho que é coisa rápida...

**Comment by lfilho** [comment]
@fernandes Agora é só com tu!

**Comment by lfilho** [comment]
@gwmoura tem notícias do Fernandes?

**Comment by gwmoura** [comment]
Vou entrar em contato com ele.

**Comment by fernandes** [comment]
sorry @12factor/pt-br estava em viagem, ja fiz o que faltava... valeu demais pessoal :)

**Comment by lfilho** [comment]
É nóis! Valeu, pessoal!! Até a próxima!

@fernandes lá no seu PR ainda tá "**Work in Progress, Please Don't Merge Yet**"

**Comment by fernandes** [comment]
mudei o título e esqueci da desc... obrigado @lfilho :)
